CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; 

CREATE TABLE users(
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    update_at TIMeSTAMP WITH TIME ZONE DEFAULT NOW()
);